service: omni-procurement

provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  versionFunctions: false
  tags: ${self:custom.tags}
  stackTags: ${self:custom.tags}
  iam:
    role:
      name: ${self:service}-${self:provider.stage}-role
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:ListBucket
          Resource: 
            - "arn:aws:s3:::omni-finance-receive-${self:provider.stage}"
            - "arn:aws:s3:::omni-finance-receive-${self:provider.stage}/*"
            - "arn:aws:s3:::omni-finance-attachment-extract-${self:provider.stage}"
            - "arn:aws:s3:::omni-finance-attachment-extract-${self:provider.stage}/*"
  runtime: nodejs14.x     
  deploymentBucket: 
    name: ${ssm:/omni-dw/${self:provider.stage}/sls/deployment/bucket}
    serverSideEncryption: AES256

custom:
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  tags:
    Application: omni-procurement
    CreatedBy: Bizcloudexperts
    Environment: ${self:custom.stage}

plugins:
 - serverless-offline

package:
  individually: true

layers:
  OmniProcurementLayer:
    path: lambdaLayer/lib
    name: ${self:service}-layer-${self:provider.stage}
    description: Omni procurement lambda layer for all node modules - ${self:provider.stage}
    compatibleRuntimes:
      - nodejs14.x
    retain: false

functions:
  omniFinanceExtractReports: ${file(config/functions/omniFinanceExtractMail.yml):function}



  