---
function:
  name: ${self:service}-trigger-gluejob-${self:provider.stage}
  description: Extracting attachments from S3 Bucket-${self:provider.stage}
  handler: src/triggerGlueJob.handler
  memorySize: 1024
  timeout: 90
  runtime: nodejs14.x 
  layers:
    - { Ref: OmniProcurementLayerLambdaLayer }
  package:
    patterns:
     - '!**/*'
     - 'src/triggerGlueJob.js'  
  # events:
  #     - s3:
  #         bucket: omni-finance-attachment-extract-${self:provider.stage}
  #         event: s3:ObjectCreated:Put
  #         rules:
  #           - prefix: Concur_open_invoices_rm/
  #       existing: true
  #       forceDeploy: true
  environment:
    OPEN_INVOICES_GLUEJOB_NAME: ${ssm:/${self:service}/${self:provider.stage}/glueJob_openInvoicesName}
    AP_TRANSACTION_GLUEJOB_NAME: ${ssm:/${self:service}/${self:provider.stage}/glueJob_apTransactionsName}
    VENDOR_TYPE_GLUEJOB_NAME: ${ssm:/${self:service}/${self:provider.stage}/glueJob_vendorTypeName}
    CRITICAL_SUPPLIER_GLUEJOB_NAME: ${ssm:/${self:service}/${self:provider.stage}/glueJob_criticalSupplierName}
    ARCHIVE_FOLDER_NAME: ${ssm:/${self:service}/${self:provider.stage}/archiveFolderName}

