---
function:
  name: ${self:service}-trigger-gluejob-${self:provider.stage}
  description: Extracting attachments from S3 Bucket-${self:provider.stage}
  handler: src/triggerGlueJob.handler
  memorySize: 1024
  timeout: 90
  runtime: nodejs14.x 
  layers:
    - { Ref: OmniProcurementLayerLambdaLayer }
  package:
    patterns:
     - '!**/*'
     - 'src/triggerGlueJob.js'  
  # events:
  #     - s3:
  #         bucket: omni-finance-attachment-extract-${self:provider.stage}
  #         event: s3:ObjectCreated:*
  #         rules:
  #           - prefix: Concur_open_invoices_rm/
  #       existing: true
  #       forceDeploy: true
  # environment:
  #   S3_BUCKET_FOLDER_OPEN_INVOICE_RM: ${ssm:/${self:service}/${self:provider.stage}/s3.attachmentExtractOpenInvoiceRm}
  #   S3_BUCKET_FOLDER_AP_TRANSCTIONS: ${ssm:/${self:service}/${self:provider.stage}/s3.attachmentExtractApTransctions}
  #   S3_BUCKET_FOLDER_VENDOR_TYPE: ${ssm:/${self:service}/${self:provider.stage}/s3.attachentExtractVendorType}
  #   S3_BUCKET_FOLDER_CRITICAL_SUPPLIERS: ${ssm:/${self:service}/${self:provider.stage}/s3.attachmentExtractCriticalSuppliers}