---
function:
  name: ${self:service}-trigger-gluejob-${self:provider.stage}
  description: Extracting attachments from S3 Bucket-${self:provider.stage}
  handler: src/triggerGlueJob.handler
  memorySize: 1024
  timeout: 90
  runtime: nodejs18.x 
  layers:
    - { Ref: OmniProcurementLayerLambdaLayer }
  package:
    patterns:
     - '!**/*'
     - 'src/triggerGlueJob.js'  
  events:
      - s3:
          bucket: omni-finance-attachment-extract-${self:provider.stage}
          event: s3:ObjectCreated:Put
          rules:
            - prefix: Concur_open_invoices_rm/
          existing: true
      - s3:
          bucket: omni-finance-attachment-extract-${self:provider.stage}
          event: s3:ObjectCreated:Put
          rules:
            - prefix: Concur_critical_suppliers/
          existing: true
      - s3:
          bucket: omni-finance-attachment-extract-${self:provider.stage}
          event: s3:ObjectCreated:Put
          rules:
            - prefix: Netsuite_ap_transactions/
          existing: true
      - s3:
          bucket: omni-finance-attachment-extract-${self:provider.stage}
          event: s3:ObjectCreated:Put
          rules:
            - prefix: Netsuite_vendor_type/
          existing: true
      - s3:
          bucket: omni-finance-attachment-extract-${self:provider.stage}
          event: s3:ObjectCreated:Put
          rules:
            - prefix: concur_Invoice_Status_Volume/
          existing: true
  environment:
    OPEN_INVOICES_GLUEJOB_NAME: ${ssm:/${self:service}/${self:provider.stage}/glueJob_openInvoicesName}
    AP_TRANSACTION_GLUEJOB_NAME: ${ssm:/${self:service}/${self:provider.stage}/glueJob_apTransactionsName}
    VENDOR_TYPE_GLUEJOB_NAME: ${ssm:/${self:service}/${self:provider.stage}/glueJob_vendorTypeName}
    CRITICAL_SUPPLIER_GLUEJOB_NAME: ${ssm:/${self:service}/${self:provider.stage}/glueJob_criticalSupplierName}
    INVOICE_STATUS_VOLUME_GLUEJOB_NAME: ${ssm:/${self:service}/${self:provider.stage}/glueJob_invoiceStatusAndVolume}
    ARCHIVE_FOLDER_NAME: ${ssm:/${self:service}/${self:provider.stage}/archiveFolderName}

